default_language_version:
  python: python3.10
default_stages: [commit, push]

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v4.0.1'
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
            files: '.'
  -   repo: https://github.com/pycqa/flake8
      rev: '4.0.1'
      hooks:
        -   id: flake8
            args: ['--max-line-length=120','--ignore=E203,E501,W503']
            files: '.'
  -   repo: https://github.com/ambv/black
      rev: '22.6.0'
      hooks:
        -   id: black
            args: ['-v','-l','119','--check']
            language_version: python3.10
            files: '.'
  -   repo: https://github.com/pycqa/isort
      rev: '5.10.0'
      hooks:
        -   id: isort
            args: ['-rc','--diff']
            files: '.'
            name: isort (python)
