# Generated by Django 4.0.6 on 2022-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'verbose_name': 'product status', 'verbose_name_plural': 'product statuses'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
